name: Lint and Format

on:
  #validate formatting and linting on direct commits or PRs to main 
  push:
    branches: [main]
  pull_request:
    branches: [main]


permissions:
  contents: read

jobs:
  lint:
    name: GDScript Lint and Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Run GDFormat Check
        #fail if formatting differs. --diff prints changes in logs to see what needs to be fixed
        run: uvx --from 'gdtoolkit==4.*' gdformat --check --diff .

      - name: Run GDLint Check
        #static linting for GDScript style and correctness rules.
        run: uvx --from 'gdtoolkit==4.*' gdlint .
