name: GDUnit4 Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read
    #timeout to prevent pipeline from running infinitely if a script deadlocks
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

      - name: Run GDUnit4 Tests
        uses: godot-gdunit-labs/gdUnit4-action@v1.3.1
        with:
          godot-version: '4.6'         
          godot-status: 'stable'           
          paths: 'res://tests' #directory where the tests are located
          #timeout for tests
          timeout: 10
          version: '6.1.3'
          retries: 3

      # - name: Upload Test Results
      #   uses: actions/upload-artifact@v4
      #   #always upload results even if tests fail so we can analyze the errors
      #   if: always()
      #   with:
      #     name: test-results
      #     path: '**/reports/**'

      - name: Publish Test Report
        uses: dorny/test-reporter@v3
        if: always()
        with:
          name: GDUnit4 Test Results
          path: "reports/**/results.xml"
          reporter: java-junit
          fail-on-error: false
          
